site_name: HPC Toolkit Front End Documentation

theme:
  name: material
  custom_dir: docs/overrides
  palette:
    primary: blue
  font:
    text: Nunito
    code: Roboto Mono
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - navigation.path
    - search.suggest
    - search.highlight
    - toc.follow
  icon:
    repo: fontawesome/brands/github
    logo: material/lan

plugins:
  - search

# repo_url: https://github.com/GoogleCloudPlatform/hpc-toolkit
# repo_name: hpc-toolkit

nav:
  - Home: index.md
  - Users:
    - User Guide: users/user_guide.md
    - Workbench User Guide: users/workbench_user_guide.md
  - Admins:
    - Admin Guide: admins/admin_guide.md
    - Advanced Admin Guide: admins/advanced_admin_guide.md
    - Cluster Guide: admins/cluster_guide.md
    - Application Guide: admins/application_guide.md
    - Workbench Admin Guide: admins/workbench_admin_guide.md
  - Developers:
    - Developer Guide: developers/developer_guide.md

extra_javascript:
  - javascripts/extra.js

extra_css:
  - stylesheets/extra.css
